name: app_two
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.7
  file_picker: ^10.1.9
  image_picker: ^0.8.7+4
  url_launcher: ^6.2.6
  open_file: ^3.3.2
  http: ^1.1.0
  mime: ^1.0.4
  path: any
  dio: ^5.4.2         # ✅ For downloading files
  path_provider: ^2.1.2  # ✅ To access device storage
  syncfusion_flutter_pdfviewer: ^29.2.9  # ✅ For PDF preview
  syncfusion_flutter_core: ^29.2.9
  table_calendar: ^3.0.9
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/default_avatar.png
    - assets/mentor_quiz.png
    - assets/goal_setup.png
    - assets/login_page.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
